// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: infoWindow.soy

/**
 * @fileoverview Templates in namespace templates.infoWindow.
 * @public
 */

goog.provide('templates.infoWindow');

goog.requireType('goog.soy');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {templates.infoWindow.getMarkerInfo.Params} opt_data
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
templates.infoWindow.getMarkerInfo = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!goog.soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {string} */
  var name = soy.asserts.assertType(typeof opt_data.name === 'string', 'name', opt_data.name, 'string');
  /** @type {string} */
  var description = soy.asserts.assertType(typeof opt_data.description === 'string', 'description', opt_data.description, 'string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div id="return"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="templates.infoWindow.getMarkerInfo infoWindow.soy:6"' : '') + '><h2>' + soy.$$escapeHtml(name) + '</h2><p>' + soy.$$escapeHtml(description) + '</p></div>');
};
/**
 * @typedef {{
 *  name: string,
 *  description: string,
 * }}
 */
templates.infoWindow.getMarkerInfo.Params;
if (goog.DEBUG) {
  templates.infoWindow.getMarkerInfo.soyTemplateName = 'templates.infoWindow.getMarkerInfo';
}
